source 'https://rubygems.org'

gem 'rails', '5.0.0'
gem "letter_opener", :group => :development
gem 'pry-rails'
gem 'faker'
gem 'json', '1.8.3'

gem 'sqlite3'
group :assets do
  gem 'sass-rails', '~> 5.0.6'
  gem 'coffee-rails', '~> 4.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'haml'
gem 'bcrypt-ruby', '3.1.2'
