source 'https://rubygems.org'
gem 'rails', '5.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.6'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2.1'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.6.0'
gem 'bootstrap-sass', '2.3.2.1'
gem 'haml-rails'
gem 'thin'
gem 'faker'
gem 'json', '1.8.3'
group :development do
  gem 'html2haml'
end
group :development, :test do
  gem 'rspec-rails'
end
group :test do
  gem 'database_cleaner'
  gem 'email_spec'
end
